### ISSUE TITLE
Code Improvements Task list

### ISSUE THREAD

**Issue by arshubham** [arshubham/srtnr#17]
- [x] Different UI components in separate modules
- [x] Remove unnecessary imports
- [x] better naming convention
- [x] use consistent trait call definition
- [x] Perform lint and reformat code.
- [x] Handle clone better
